trigger:

- master

pool:
  vmImage: ubuntu-latest

stages:

# - stage: Build_docker_image
#   displayName: Build docker image 
#   jobs:

#   - job: Get_Version
#     displayName: Get Version Build 
#     pool:
#       vmImage: ubuntu-latest 
#     steps:

#     - task: CmdLine@2
#       displayName: Comparaison version application
#       inputs:
#         script: |
#           versionnew=$(cat azure-vote/main.py | grep -E "^ver = \"[0-9.]+\"\$"|awk -F\" {'print $2'})
#           versionold=$(curl -s http://lain-brief8.westeurope.cloudapp.azure.com | grep -o 'Azure Voting App v[0-9]\+\.[0-9]\+\.[0-9]\+' | sed 's/^.*v//;s/ on.*$//' | head -n1)
#           echo "##vso[task.setvariable variable=verold]$versionold"
#           echo "##vso[task.setvariable variable=vernew]$versionnew"
  
#     - task: Docker@2
#       name: CreateDockerImage
#       displayName: create dockerhub image
#       condition: ne(variables.verold,variables.vernew)
#       inputs:
#         containerRegistry: 'container-connection'
#         repository: 'alaincpn/voteapp'
#         command: 'buildAndPush'
#         Dockerfile: 'Dockerfile'
#         tags: 'latest'

- stage: Test_Deployment
  displayName: testdep
  jobs:
  - job: Test_Deploy
    displayName: Deploy on Test 
    pool:
      vmImage: 'ubuntu-latest' 
    steps:

    - task: KubernetesManifest@0
      name: kuberneTest
      displayName: deploy on testing ns
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'aks-connection'
        namespace: 'testenv'
        manifests: '**/app/test/*'

    - task: Bash@3
      name: waitingfordeploy
      condition: succeeded()
      displayName: waiting for deployment
      inputs:
        targetType: 'inline'
        script: 'sleep 1'

    # - task: CmdLine@2
    #   name : testcharge
    #   displayName: Test charge sur qal
    #   inputs:
    #     script: |
    #       seq 250 | parallel --max-args 0  --jobs 20 "curl -k -iF 'vote=free' http://lain-brief8.westeurope.cloudapp.azure.com"

    # - task: CmdLine@2
    #   name: waitforcharge
    #   inputs:
    #     script: 'sleep 60'

    # - task: Kubernetes@1
    #   name : recupNbPods
    #   inputs:
    #     connectionType: 'Kubernetes Service Connection'
    #     kubernetesServiceEndpoint: 'aks-connection'
    #     namespace: 'qal'
    #     command: 'get'
    #     useConfigurationFile: true
    #     configuration: './app/qal/app.yml'
    #     secretType: 'dockerRegistry'
    #     containerRegistryType: 'Azure Container Registry'

    # - task: CmdLine@2
    #   name: nbpod
    #   inputs:
    #     script: |
    #       nbrpod=$(echo $RECUPNBPODS_KUBECTLOUTPUT | jq '.items[0].spec.replicas')
    #       echo $nbrpod
    #       echo "##vso[task.setvariable variable=podnumber;isOutput=true]$nbrpod"
    # - task: CmdLine@2
    #   condition: ne(variables['podnumber'],2)
    #   name: scalework
    #   inputs:
    #     script: echo 'Scaling complete'

- stage: dependency_check
  displayName: Run dependency check
  jobs:

  - job: dep_check
    displayName: Dependency check
    
    steps:
      - task: dependency-check-build-task@6
        inputs:
          projectName: 'SecurityScan'
          scanPath: '**'
          format: 'JUNIT'
          reportFilename: 'testreport'
          failOnCVSS: '8'
          additionalArguments: 

      # - task: CmdLine@2
      #   displayName: check-nb-dependencies
      #   inputs:
      #     script: |
      #       resultest="$(cat /home/vsts/work/1/TestResults/dependency-check/testreport/dependency-check-report.html)"
      #       echo "#####DEBUG#####"
      #       echo $resultest
      #       echo "##vso[task.setvariable variable=restest]$resultest"

