# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: kubesetup
  jobs:
  - job: connectkube
    steps:

    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'aks-connection'
        namespace: 'qal'
        command: 'get'
        arguments: 'deployments'
        secretType: 'dockerRegistry'
      name: "k8s"

# Appel du script de récupération des variables :

- stage: scripts
  jobs:
  - job: getvars
    steps:
    - task: Bash@3
      inputs:
        filePath: 'qalscript.sh'

- stage: docker
  jobs:
  - job: buildandpush
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'container-connection'
        repository: 'alaincpn/voteapp'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
        tags: |
          $(scrversion)

- stage: qal
  jobs:
  - job: qaldeploy
    steps: 
    - task: KubernetesManifest@0
      name: qaldeploy
      displayName: 'qaldeploy'
      condition: ne(variables['kubeoutpversion'],variables['scrversion'])
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'aks-connection'
        namespace: 'qal'
        manifests: 'app/app.yml'
        rolloutStatusTimeout: '60'

- stage: qalfail
  jobs:
  - job: qalhasfailed
    dependsOn: qaldeploy
    condition: failed()
    steps:
      - script: echo "Qal has failed !"

- stage: qalpass
  jobs:
  - job: qalhaspassed
    dependsOn: qaldeploy
    condition: succeded()
    steps:
      - script: echo "Qal has passed !"
  
  - job: kubecanary
    steps:
    - task: KubernetesManifest@0
      name: kubecanary
      condition: ne(variables['kubeoutpversion'],variables['scrversion'])
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'aks-connection'
        namespace: 'prod'
        strategy: 'canary'
        percentage: '10'
        manifests: 'app/app.yml'
        rolloutStatusTimeout: '60'