apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redisclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: redisstorapiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redisclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: redisstor